# Generated by Django 4.2.1 on 2023-05-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
